image: python:3
test:
  script:
    # this configures Django application to use attached postgres database that is run on `postgres` host
    - apt-get update -qy
    - pip install -r requirements.txt
    - python manage.py test

staging:
  type: deploy
  image: ruby
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=tdt4242-t26 --api-key=80d2a6a3-ab13-4e31-b84a-d302b538e68a
  only:
    - master
#https://docs.gitlab.com/ee/ci/examples/test-and-deploy-python-application-to-heroku.html
